### ISSUE TITLE
primitive neighbor list

### ISSUE THREAD

**Issue by moradza** [m3g/CellListMap.jl#68]
Hi,

Do you have support for primitive neighbor list? https://wiki.fysik.dtu.dk/ase/_modules/ase/neighborlist.html 

I am also using CellListMap in python, memory copy takes long time from list to numpy and torch, is it possible to return numpy array direclty?

Best

**Comment by lmiq** [comment]
Can you tell me a little bit more about your problem? I guess that is not the conversion that takes time, but the fact that new lists of neighbors are created (a new array is allocated) on every call (the return type of the neighborlist function is equivalent to an `np.array([], dtype="i,i,f")`.

It is of course possible to implement an `inplace` version of the neighborlist function, which will be faster on successive calls, and that is something that I almost implemented several times, so you can perhaps give me the motivation to do it, it wouldn't take me more than a couple of days.

But, in general, one uses the neighbor list for for something, and with celllistmap you can compute that directly without even having to build the list, which is even faster.

> Do you have support for primitive neighbor list? https://wiki.fysik.dtu.dk/ase/_modules/ase/neighborlist.html

I read that, but I didn't get what exactly do you want that is not already given by the neighborlist function we have.

**Comment by moradza** [comment]
The motivation for my work is this for each frame of trajectory, I need to compute neighbor list. This neighborlist should be converted to an edge_index = torch.tensor of shape (2, -1). And I should move it to gpu, julia computation time gives me a speed up of 180 times but the conversion of list to torch.tensor reduces speed up to 2 times faster. 
I am newbie when it comes to Julia, but return type of CellListMap is a list on python not a numpy array, am I right?

> I read that, but I didn't get what exactly do you want that is not already given by the neighborlist function we have.

This is not primary issue right now. This is the case with crystals, where unit cell is smaller than the cutoff. We have to repeat the system on the fly (kx, ky, kz) times to get neighbor list up to cutoff.

**Comment by lmiq** [comment]
> This neighborlist should be converted to an edge_index = torch.tensor of shape (2, -1). And I should move it to gpu, julia computation time gives me a speed up of 180 times but the conversion of list to torch.tensor reduces speed up to 2 times faster.

Maybe we could try to return exactly that already. How can I generate one of such tensors in Python (I don't use torch)? 

The return type of CellListMap is, I think, the equivalent of a numpy array with a custom dtype. That I can check and I will implement the inplace version of neighborlist, which will receive such array as a parameter and updated it. I think that, in principle, that will be easy. 

> This is the case with crystals, where unit cell is smaller than the cutoff

Uhm... no, currently we do not support that. I never thought of that possibility. That is not straightforward to implement, no, for the moment the only idea that comes into my mind is to replicate the system. From a first sight, I think I would need to define two unitcells. I'll think about that.

**Comment by moradza** [comment]
Thanks for the codes, I will run them this week to benchmark their performance. 

`I also tested preallocating all data, but that had a minor implication only`

My test also shows no improvement with pre-allocation.

**Comment by moradza** [comment]
It works fine and I have 20-100 x faster neighbor list generation! Closing this.

**Comment by lmiq** [comment]
Nice, thanks for the feedback. I will add something like that to the user guide.

**Comment by lmiq** [comment]
I've added a simpler interface for Python users here:

https://m3g.github.io/CellListMap.jl/stable/python/

You may be able to run the julia code multi-threaded as well, and get some additional speedup.
