### ISSUE TITLE
Suggestion: Is it possible to output the coordinates and size of cells so one can visualize them?

### ISSUE THREAD

**Issue by AhmedSalih3d** [m3g/CellListMap.jl#76]
Hello!

Thank you for the help :)

Something similar to this in a sense:

![image](https://user-images.githubusercontent.com/36305327/210153234-dcace9fd-0f24-42da-b1fb-78e9ff2bcfa9.png)

So that one can visualize the grid used for the neighbour search. I know it is uniform cells and the cell width is 2x cutoff, but could not find the cell center coordinates

Kind regards

**Comment by lmiq** [comment]
There is an internal testing function for that:
```
using Plots
using CellListMap
x, box = CellListMap.xatomic(10^4) # example
CellListMap.draw_computing_cell(x,box)
```

but note that this is internal and created only for testing. Do not expect that it necessarily works flawlessly or keeps available for ever.

**Comment by AhmedSalih3d** [comment]
Thank you very much!

I will have a look at the source code for that function
