### ISSUE TITLE
Suggestion: In a transient simulation, based on the first time step, can I define a "box of interest"?

### ISSUE THREAD

**Issue by AhmedSalih3d** [m3g/CellListMap.jl#77]
Hello!

In my simulations I often need to define a "box of interest", i.e. any particle which ends up outside this box will be removed from the simulation. I was wondering if there was a way to specify this using this package?

For example for a dam break simulation:

![image](https://user-images.githubusercontent.com/36305327/210153307-67f03ab6-aeaa-4e69-a3c8-31cf481465ce.png)

I would like any particle leaving the red box to leave the simulation. 

I could properly do this using a package to find the bounding box, then a manual check each time step if any particles has left the domain.

I thought it might be of use for others as well, so that is why I suggest it :)

Kind regards

**Comment by lmiq** [comment]
I would suggest implementing that internally in your package, for example creating a property for each particle that carries that information and skipping computations among particles that are outside the box in the mapped function.

**Comment by AhmedSalih3d** [comment]
Thank you for the feedback! 😊
